apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  labels:
    app.kubernetes.io/instance: argocd
  name: argocd
  namespace: argocd
spec:
  dex:
    openShiftOAuth: true
  server:
    route:
      enabled: true
  initialRepositories: >
    - url:
    https://github.com/hybridpollo/ocs4argocd
  rbac:
    defaultPolicy: ""
