# Info https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/1.7-1.8/#health-assessement-of-argoprojioapplication-crd-has-been-removed
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  
  resource.customizations.health.argoproj.io_Application: |
    hs = {}
    hs.status = 'Progressing'
    hs.message = ''
    if obj.status ~= nil then
      if obj.status.health ~= nil then
        hs.status = obj.status.health.status
          if obj.status.health.message ~= nil then
            hs.message = obj.status.health.message
          end
      end
    end
    return hs
