apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-ocs-infra
  namespace: argocd
spec:
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
