apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-storage
commonLabels:
  app.kubernetes.io/part-of: dev-ocs-infra

resources:
  - resources/ocs-storage-cluster.yaml
  - resources/cephblockpool-r2.yaml
  - resources/storageclass-rbd-r2.yaml
