---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-local-storage
commonLabels:
  app.kubernetes.io/part-of: dev-ocs-infra

resources:
  - resources/lso-auto-discovery.yaml
  - resources/lso-ocs-volumeset.yaml
