---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ocs-subscription
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: '12'
spec:
  name: ocs-operator
  channel: 'stable-4.8'
  installPlanApproval: Manual
  source: redhat-operators
  sourceNamespace: openshift-marketplace
