apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-storage
commonLabels:
  app.kubernetes.io/part-of: dev-ocs-infra

resources:
  - resources/ocs-namespace.yaml
  - resources/ocs-operator-group.yaml
  - resources/ocs-subscription.yaml
#  - resources/odf-subscription.yaml
